# which benchmarks to run
benchmarks = '../benchmarks/**/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}"
]

[runs.dead_store_analysis]
pipeline = [
    "bril2json",
    "python3 alias_analysis.py --dsa",
    "brili -p {args}"
]

[runs.store_to_forward]
pipeline = [
    "bril2json",
    "python3 alias_analysis.py --stf",
    "brili -p {args}"
]

[runs.redundant_load_elimination]
pipeline = [
    "bril2json",
    "python3 alias_analysis.py --rle",
    "brili -p {args}"
]

[runs.alias_full]
pipeline = [
    "bril2json",
    "python3 alias_analysis.py --dse --rle --stf",
    "brili -p {args}"
]

