# which benchmarks to run
benchmarks = '../benchmarks/**/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "python3 ../examples/to_ssa.py",
  "brili -p {args}"
]

[runs.to_ssa_constant_liveness]
pipeline = [
  "bril2json",
  "python3 ../examples/to_ssa.py",
  "python3 constant_folding.py",
  "python3 global_liveness.py",
  "brili -p {args}"
]

[runs.licm]
pipeline = [
  "bril2json",
  "python3 ../examples/to_ssa.py",
  "python3 loop_invariant_code_motion.py",
  "brili -p {args}"
]

[runs.licm_folding_dce]
pipeline = [
  "bril2json",
  "python3 ../examples/to_ssa.py",
  "python3 loop_invariant_code_motion.py",
  "python3 constant_folding.py",
  "python3 global_liveness.py",
  "brili -p {args}"
]